language: go

go: "1.11"
os: "linux"
dist: trusty
sudo: false
install: true

script:
- env GO111MODULE=on go test --godog.tags=~wip
- env GO111MODULE=on go test -v sdk/cli
- env GO111MODULE=on go test -v sdk/env
- env GO111MODULE=on go build
